# Generated by Django 2.2.7 on 2019-12-04 14:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=64, null=True, verbose_name='标题')),
                ('content', models.CharField(default='', max_length=1024, null=True, verbose_name='内容')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('todo_status', models.BooleanField(default=True, verbose_name='处理状态')),
            ],
        ),
    ]
